GET http://localhost:3003/api/blogs
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QgdXNlciAyIiwiaWQiOiI2Njk2NWI3N2Y0MWI2OGYyZGFmMDBlZGEiLCJpYXQiOjE3MjExMjk4ODR9.x4KJYdA_SnmeR1pfcCBYOmhbFOL8IowSQKzO4f-L24E

