services:
  todo-backend:
    image: back-dev
    volumes:
      - ./todo-backend:/usr/src/app
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - mongo
      - redis
    container_name: backend-dev
    
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: the_username
      MONGO_INITDB_ROOT_PASSWORD: the_password
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./todo-backend/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - /mongo_data:/data/db
  redis:
    image: redis

  todo-frontend:
    image: front-dev
    volumes:
      - ./todo-frontend:/usr/src/app
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api
    container_name: frontend-dev

  nginx:
    image: nginx:1.20.1
    ports:
      - 8080:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - todo-frontend
      - todo-backend
    container_name: reverse-proxy

volumes:
  mongo_data:
  redis_data: