services:
  todo-backend:
    image: back-prod
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - mongo
      - redis
    container_name: backend-prod

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: the_username
      MONGO_INITDB_ROOT_PASSWORD: the_password
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./todo-backend/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
    container_name: mongo-prod

  redis:
    image: redis
    volumes:
      - redis_data:/data
    container_name: redis-prod

  todo-frontend:
    image: front-prod
    container_name: frontend-prod

  nginx:
    image: nginx:1.20.1
    ports:
      - 80:80
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - todo-frontend
      - todo-backend
    container_name: nginx-prod

volumes:
  mongo_data:
  redis_data: